apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: vcodeworkspaces.davidp1404.github.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: davidp1404.github.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                resources:
                  type: object                
                  properties:
                    requests:
                      type: object
                      default: {}
                      properties:
                        cpu: 
                          type: string
                          default: "1"
                        memory:
                          type: string
                          default: "1Gi"
                    limits:
                      type: object
                      default: {}
                      properties:
                        cpu: 
                          type: string
                          default: "1"
                        memory:
                          type: string
                          default: "1Gi"                      
                storageClassName:
                  type: string     
                volumeSize:
                  type: string
                  default: "2Gi"
                password:
                  type: string
                ingress-host:
                  type: string
                  default: ""
                ingress-class:
                  type: string
                  default: "nginx"
                image:
                  type: string
                  default: "codercom/code-server"
              required:
                 - storageClassName
                 - volumeSize
                 - password
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      # - name: path
      #   type: string
      #   description: URL/<path>
      #   jsonPath: .spec.path
      - name: storageClassName
        type: string
        description: storageClassName
        jsonPath: .spec.storageClassName
      - name: volumeSize
        type: string
        description: volumeSize
        jsonPath: .spec.volumeSize
      - name: resources
        type: string
        description: resources
        jsonPath: .spec.resources
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp 
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: vcodeworkspaces
    # singular name to be used as an alias on the CLI and for display
    singular: vcodeworkspace
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: vcodeWorkspace
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - vcws
